apiVersion: v1
kind: Service
metadata:
  name: client-equivvy-webapp-react
  namespace: test-equivvy
  labels:
    name: client-equivvy-webapp-react
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: client-equivvy-webapp-react

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: client-equivvy-webapp-react
  namespace: test-equivvy
  labels:
    app: client-equivvy-webapp-react
    service: client-equivvy-webapp-react
spec:
  selector:
    matchLabels:
      app: client-equivvy-webapp-react
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: client-equivvy-webapp-react
        date: "1545478396"
    spec:
      imagePullSecrets:
      - name: regcred
   
      containers:
      - name: client-equivvy-webapp-react
        imagePullPolicy: "Always"
        image: 381850379063.dkr.ecr.us-east-1.amazonaws.com/client-equivvy-webapp-react:latest
        command: ['npm']
        args: ['start']
        ports:
        - containerPort: 3000
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "3000"
      restartPolicy: Always

